- GoogleApi/Entities/Places/Add/Request/PlacesAddRequest.cs
- GoogleApi/Entities/Places/Common/Prediction.cs
- GoogleApi/Entities/Places/Details/Response/DetailsResult.cs
see https://github.com/vivet/GoogleApi/issues/69
and https://github.com/vivet/GoogleApi/issues/50
> Fallback on `unknown` when place location type deserialization fails

- GoogleApi/Entities/BaseRequest.cs
- GoogleApi/Entities/Maps/BaseMapsRequest.cs
@vivet removed updates, made minimum changes.
* Fixed digital signature generation to SHA1.
* Switched base url to maps.googleapis.com [https://mapsplatform.googleblog.com/2011/10/a-grab-bag-of-maps-api-news.html]
> feature_premium_plan_license

- GoogleApi/Entities/Places/Search/Find/Request/PlacesFindSearchRequest.cs
Without the "locationbias" key in the query string I kept getting "ZERO_RESULTS" back from the API. 
https://developers.google.com/places/web-service/search#FindPlaceRequests
> add locationbias to parameters keys

- GoogleApi/Entities/Places/Search/Common/Enums/SearchPlaceType.cs
ElectronicsStore in SearchPlaceType has invalid Value in EnumMember attribute.
> Fixed invalid EnumMember.Value in ElectronicsStore value.

- GoogleApi/Entities/Maps/Roads/BaseRoadsResponse.cs
The Roads API sometimes returns a warningMessage field along with the dataset. This happens if the result quality is lacking due to the input points being too sparse.
This PR exposes that field.
> Added WarningMessage to BaseRoadsResponse

- .tests/GoogleApi.Test/Maps/Geocoding/Address/AddressGeocodeTests.cs
- GoogleApi/Entities/Maps/Geocoding/Address/Request/AddressGeocodeRequest.cs
Turns out the correct order is sw|ne...
> Fix bounds order when geocoding an address

- .tests/GoogleApi.Test/Maps/Directions/DirectionsTests.cs
- .tests/GoogleApi.UnitTests/Maps/Directions/DirectionsRequestTests.cs
- GoogleApi/Entities/Maps/Common/Enums/AvoidWay.cs
Ferry avoidance was missing from the enum.
cf https://developers.google.com/maps/documentation/directions/intro?hl=ja#Restrictions
> Support avoiding ferries

- GoogleApi/GoogleApi.csproj
This package should provide at least a 2.0 target. I added the usual list.
cf https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting
> Target more recent .NET Standard platforms

- GoogleApi/Entities/Places/Details/Request/PlacesDetailsRequest.cs
- GoogleApi/Entities/Places/Search/Find/Request/PlacesFindSearchRequest.cs
- GoogleApi/Entities/Search/Video/BaseVideoSearchRequest.cs
We have clients from Azerbaijan and they have reported errors in our app. We are requesting place's details through the Google Places API. 
Error message: Error while parsing 'fields' parameter: Unexpected characters
Azerbaijani alphabet (plus Turkish, Kazakh and possibly others) have casing rules that differ from the English ones. Specifically, they have separate dotted (small U+0069 and capital U+0130) and dotless (small U+0131 and capital U+0049) letters I. When lower-casing from dotless capital I (U+0049) we get dotless small ı (U+0131) and not the dotted small i (U+0069).
Tested on our Android (Xamarin.Android) app.
P.S. Thanks for your hard work!
> Enum to String using invariant culture

- GoogleApi/Entities/Maps/Directions/Response/Enums/ManeuverAction.cs
Hi!
I noticed a typo in maneuver action "Keep left" and I fixed it.
Regards
> Fix type in maneuver action member name

- GoogleApi/Entities/Common/Enums/AddressComponentType.cs
- GoogleApi/Entities/Common/Enums/PlaceLocationType.cs
I've added `plus_code` as a new address component type as can be seen in docs [here](https://developers.google.com/maps/documentation/geocoding/overview#Types) and as a new place location type as can be seen in docs [here](https://developers.google.com/maps/documentation/places/web-service/supported_types#table2).
Sample request returning `plus_code` types which are being mapped to `Unknown` due to missing corresponding enum member:
> https://maps.googleapis.com/maps/api/geocode/json?latlng=52.511597,-1.777308&key=YOUR_KEY
Sorry for the white space removal, that's automatically done by my VS extension. If that's a problem I can bring it back.
> Missing plus code in enums

- GoogleApi/Entities/Places/Search/Find/Response/Candidate.cs
The current Candidate response object is missing the "types" array. I'm adding this field in the PR
> Missing Types array on Places Candidate response

- GoogleApi/Entities/Common/Enums/Status.cs
Add the `OVER_DAILY_LIMIT` to the `Status` enumeration. Used https://developers.google.com/maps/documentation/geocoding/overview#StatusCodes as source.
> Add OVER_DAILY_LIMIT status to enum

- GoogleApi/Entities/Common/Enums/Status.cs
Add the `MAX_DIMENSIONS_EXCEEDED` to the Status enumeration. Used https://developers.google.com/maps/documentation/distance-matrix/overview#DistanceMatrixStatus as source.
> Add MAX_DIMENSIONS_EXCEEDED to Status enum

- .tests/GoogleApi.UnitTests/Translate/Common/Extensions/LanguagesExtensionTests.cs
- .tests/GoogleApi.UnitTests/Translate/Translate/TranslateRequestTests.cs
- GoogleApi/Entities/Translate/Common/Enums/Extensions/LanguageExtension.cs
- GoogleApi/Entities/Translate/Common/Enums/Language.cs
All translate unit tests completed successfully after adding the Mizo language, updating the language extensions to match the current NMT model, and then updated the various tests to support the extension updates.
> 302 language support updates

- .tests/GoogleApi.UnitTests/Translate/Languages/LanguagesRequestTests.cs
- GoogleApi/Entities/Translate/Common/Enums/Converters/LanguageEnumConverter.cs
- GoogleApi/Entities/Translate/Common/Enums/Extensions/EnumExtension.cs
- GoogleApi/Entities/Translate/Common/Enums/Language.cs
- GoogleApi/Entities/Translate/Languages/Response/SupportedLanguage.cs
The current StringEnumConverter throws an exception whenever google adds a new language (we ran into this with #302 when they added 'lus' and then again almost immediately when they added 'jv' as an alternative language code for Javanese). This pull request creates a custom enum converter for parsing the incoming list and assigning unknown codes to a new Language.Unsupported value. 
This shouldn't be an issue in other places since the only place this was used was during the creation of the Response specifically for SupportedLanguages calls.
I'm honestly not sure how to automatically reconcile this long term, but the frequency that google has been adding languages and breaking this call is distressing. Additionally with alternative language codes like we are seeing for Javanese (they …
> Non breaking language enum handling

- GoogleApi/Entities/Common/Enums/BusinessStatus.cs
I didn't save the new Test for this, but a live call to the API was successfully able to parse the response for this call without exception. I figure we can add it and update when google responds to the issue or updates the documentation: https://issuetracker.google.com/issues/249164721
> Added the Future_Opening status to the BusinessStatus enum.

- GoogleApi/Entities/Common/Enums/BusinessStatus.cs
Causing deserialization failure as the business status:
System.Text.Json.JsonException: The JSON value 'CLOSED_TEMPORARILY' could not be converted to GoogleApi.Entities.Common.Enums.BusinessStatus.
string returned by google is:
"business_status" : "CLOSED_TEMPORARILY",
> Fix CLOSED_TEMPORARELY typo

- .tests/GoogleApi.Test/Maps/DistanceMatrix/DistanceMatrixTests.cs
- GoogleApi/Entities/Maps/DistanceMatrix/Request/DistanceMatrixRequest.cs
When it sends upper-case `WALKING` value for `mode` query parameter this value is ignored and results for default `DRIVING` mode are returned.
Changing it to lower-case `walking` value fixes the issue.
Assume bug was introduced in fix for #386 issue.
> Mode parameter lower-case in Distance Matrix

- GoogleApi/Entities/Common/Converters/StringSecondsTimeSpanJsonConverter.cs
The Write method in StringSecondsTimeSpanJsonConverter is missing, causing exceptions when serializing data back to JSON. Implement the missing method.
> Add missing serializer method

- GoogleApi/Entities/PlacesNew/Common/Place.cs
- GoogleApi/Entities/PlacesNew/Search/Text/Response/PlacesNewTextSearchResponse.cs
Fixed some issues for the Places (new) API:
- `PrimaryType` default null in the response class (instead of the default enum value `CarDealer`). Related to #408
- When the response of the text search API is empty, the `Places` property should be an empty list instead of null (in my opinion, let me know if you disagree).
> Bug: PrimaryType default null, Places default empty list
